Repository connetist/connectist-backend, pull requests merged in 2024-06, with the labels that each got.

#3 feat : 채팅서버 생성 및 폴더 분리, 임의 테스트코드 작성
  chat-service/src/main/java/org/example/chatservice/controller/ChatController.java
  chat-service/src/main/java/org/example/chatservice/domain/ChatMember.java
  chat-service/src/main/java/org/example/chatservice/domain/ChatRoom.java
  chat-service/src/main/java/org/example/chatservice/infrastructure/entity/ChatMemberEntity.java
  chat-service/src/main/java/org/example/chatservice/infrastructure/entity/ChatRoomEntity.java
  chat-service/src/main/java/org/example/chatservice/infrastructure/repository/ChatRepository.java
  chat-service/src/main/java/org/example/chatservice/service/ChatService.java
  chat-service/src/main/java/org/example/chatservice/service/ChatServiceImpl.java
  chat-service/src/test/java/org/example/chatservice/chatRoom/domain/ChatRoomtTest.java
  chat-service/src/test/java/org/example/chatservice/chatRoom/service/ChatRoomServiceTest.java
Labels: 구현

#4 docs : README 작성
  README.md
Labels: 문서

#11 docs : testcode coverage report를 github action과 연동
  .github/workflows/chat-service-deployyml
Labels: 문서, 배포

#20 [FEAT] 유저 회원가입 인증메일 전송 구현
  user-service/.gitignore
  user-service/build.gradle
  user-service/gradle/wrapper/gradle-wrapper.jar
  user-service/gradle/wrapper/gradle-wrapper.properties
  user-service/gradlew
  user-service/gradlew.bat
  user-service/settings.gradle
  user-service/src/main/java/com/example/userservice/UserServiceApplication.java
  user-service/src/main/java/com/example/userservice/user/controller/UserCreateController.java
  user-service/src/main/java/com/example/userservice/user/controller/port/JoinUserService.java
  user-service/src/main/java/com/example/userservice/user/controller/port/UserService.java
  user-service/src/main/java/com/example/userservice/user/controller/response/UserJoinResponse.java
  user-service/src/main/java/com/example/userservice/user/domain/User.java
  user-service/src/main/java/com/example/userservice/user/domain/UserCreate.java
  user-service/src/main/java/com/example/userservice/user/domain/UserSchool.java
  user-service/src/main/java/com/example/userservice/user/domain/UserStatus.java
  user-service/src/main/java/com/example/userservice/user/domain/UserUpdate.java
  user-service/src/main/java/com/example/userservice/user/domain/join/JoinUser.java
  user-service/src/main/java/com/example/userservice/user/infrastructure/MailSenderImpl.java
  user-service/src/main/java/com/example/userservice/user/infrastructure/join/JoinUserConcurrentMapRepository.java
  user-service/src/main/java/com/example/userservice/user/infrastructure/join/JoinUserRepository.java
  user-service/src/main/java/com/example/userservice/user/service/CertificationService.java
  user-service/src/main/java/com/example/userservice/user/service/JoinUserServiceImpl.java
  user-service/src/main/java/com/example/userservice/user/service/port/MailSender.java
  user-service/src/main/java/com/example/userservice/util/uuid/SystemUuidHolder.java
  user-service/src/main/java/com/example/userservice/util/uuid/UuidHolder.java
  user-service/src/test/java/com/example/userservice/UserServiceApplicationTests.java
  user-service/src/test/java/com/example/userservice/user/infrastructure/MailSenderImplTest.java
Labels: 구현

#23 [Chore] PR 템플릿 수정
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 문서, 세팅

#30 [FEAT] User 회원가입 certification code 인증 구현
  user-service/build.gradle
  user-service/src/main/java/com/example/userservice/UserServiceApplication.java
  user-service/src/main/java/com/example/userservice/config/AppConfig.java
  user-service/src/main/java/com/example/userservice/user/controller/UserCreateController.java
  user-service/src/main/java/com/example/userservice/user/controller/port/JoinUserService.java
  user-service/src/main/java/com/example/userservice/user/controller/port/UserService.java
  user-service/src/main/java/com/example/userservice/user/controller/response/UserJoinResponse.java
  user-service/src/main/java/com/example/userservice/user/domain/User.java
  user-service/src/main/java/com/example/userservice/user/domain/UserCreate.java
  user-service/src/main/java/com/example/userservice/user/domain/UserSchool.java
  user-service/src/main/java/com/example/userservice/user/domain/UserStatus.java
  user-service/src/main/java/com/example/userservice/user/domain/join/JoinUser.java
  user-service/src/main/java/com/example/userservice/user/domain/join/JoinUserCertification.java
  user-service/src/main/java/com/example/userservice/user/domain/join/JoinUserCreate.java
  user-service/src/main/java/com/example/userservice/user/domain/user/School.java
  user-service/src/main/java/com/example/userservice/user/domain/user/UserDegree.java
  user-service/src/main/java/com/example/userservice/user/domain/user/UserMajor.java
  user-service/src/main/java/com/example/userservice/user/domain/user/UserSex.java
  user-service/src/main/java/com/example/userservice/user/domain/user/UserStatus.java
  user-service/src/main/java/com/example/userservice/user/infrastructure/UserEntity.java
  user-service/src/main/java/com/example/userservice/user/infrastructure/UserMongoRepository.java
  user-service/src/main/java/com/example/userservice/user/infrastructure/UserRepositoryImpl.java
  user-service/src/main/java/com/example/userservice/user/service/CertificationService.java
  user-service/src/main/java/com/example/userservice/user/service/JoinUserServiceImpl.java
  user-service/src/main/java/com/example/userservice/user/service/UserServiceImpl.java
  user-service/src/main/java/com/example/userservice/user/service/port/UserRespository.java
  user-service/src/main/java/com/example/userservice/util/certification/CertificationDigitHolder.java
  user-service/src/main/java/com/example/userservice/util/certification/CertificationHolder.java
  user-service/src/main/java/com/example/userservice/util/certification/CertificationUuidHolder.java
  user-service/src/main/java/com/example/userservice/util/clock/ClockHolder.java
  user-service/src/main/java/com/example/userservice/util/clock/SystemClockHolder.java
  user-service/src/main/java/com/example/userservice/util/exception/InputErrorException.java
  user-service/src/main/java/com/example/userservice/util/exception/NotFoundException.java
  user-service/src/main/java/com/example/userservice/util/uuid/UuidHolder.java
  user-service/src/test/java/com/example/userservice/user/service/JoinUserServiceImplTest.java
Labels: 구현

#34 [FEAT] 유저 회원가입 이메일 인증 및 중복 인증 request 방지 구현하기
  user-service/src/main/java/com/example/userservice/user/controller/UserCreateController.java
  user-service/src/main/java/com/example/userservice/user/controller/response/UserJoinResponse.java
  user-service/src/main/java/com/example/userservice/user/domain/User.java
  user-service/src/main/java/com/example/userservice/user/domain/join/JoinUser.java
  user-service/src/main/java/com/example/userservice/user/domain/join/JoinUserCertification.java
  user-service/src/main/java/com/example/userservice/user/infrastructure/join/JoinUserConcurrentMapRepository.java
  user-service/src/main/java/com/example/userservice/user/infrastructure/join/JoinUserRepository.java
  user-service/src/main/java/com/example/userservice/user/service/CertificationService.java
  user-service/src/main/java/com/example/userservice/user/service/JoinUserServiceImpl.java
  user-service/src/main/java/com/example/userservice/util/certification/email/EmailCertification.java
Labels: 구현

#37 [FIX] Joinuser Null 오류 해결
  user-service/build.gradle
  user-service/src/main/java/com/example/userservice/config/SecurityConfig.java
  user-service/src/main/java/com/example/userservice/user/controller/UserController.java
  user-service/src/main/java/com/example/userservice/user/controller/UserCreateController.java
  user-service/src/main/java/com/example/userservice/user/controller/port/JoinUserService.java
  user-service/src/main/java/com/example/userservice/user/controller/port/UserService.java
  user-service/src/main/java/com/example/userservice/user/domain/User.java
  user-service/src/main/java/com/example/userservice/user/domain/create/UserCreate.java
  user-service/src/main/java/com/example/userservice/user/domain/create/UserCreateDto.java
  user-service/src/main/java/com/example/userservice/user/infrastructure/UserEntity.java
  user-service/src/main/java/com/example/userservice/user/infrastructure/join/JoinUserConcurrentMapRepository.java
  user-service/src/main/java/com/example/userservice/user/infrastructure/join/JoinUserRepository.java
  user-service/src/main/java/com/example/userservice/user/service/JoinUserServiceImpl.java
  user-service/src/main/java/com/example/userservice/user/service/UserServiceImpl.java
  user-service/src/main/java/com/example/userservice/util/clock/ClockHolder.java
  user-service/src/main/java/com/example/userservice/util/clock/SystemClockHolder.java
  user-service/src/main/java/com/example/userservice/util/id/IdGenerator.java
  user-service/src/main/java/com/example/userservice/util/id/IdGeneratorByUUID.java
  user-service/src/test/java/com/example/userservice/user/service/JoinUserServiceImplTest.java
Labels: 버그

#36 [FEAT] 유저 로그인 구현하기 & 도메인 구성 요소 변경하기
  user-service/build.gradle
  user-service/src/main/java/com/example/userservice/config/SecurityConfig.java
  user-service/src/main/java/com/example/userservice/user/controller/UserController.java
  user-service/src/main/java/com/example/userservice/user/controller/UserCreateController.java
  user-service/src/main/java/com/example/userservice/user/controller/port/JoinUserService.java
  user-service/src/main/java/com/example/userservice/user/controller/port/UserService.java
  user-service/src/main/java/com/example/userservice/user/domain/User.java
  user-service/src/main/java/com/example/userservice/user/domain/create/UserCreate.java
  user-service/src/main/java/com/example/userservice/user/domain/create/UserCreateDto.java
  user-service/src/main/java/com/example/userservice/user/infrastructure/UserEntity.java
  user-service/src/main/java/com/example/userservice/user/infrastructure/join/JoinUserConcurrentMapRepository.java
  user-service/src/main/java/com/example/userservice/user/infrastructure/join/JoinUserRepository.java
  user-service/src/main/java/com/example/userservice/user/service/JoinUserServiceImpl.java
  user-service/src/main/java/com/example/userservice/user/service/UserServiceImpl.java
  user-service/src/main/java/com/example/userservice/util/clock/ClockHolder.java
  user-service/src/main/java/com/example/userservice/util/clock/SystemClockHolder.java
  user-service/src/main/java/com/example/userservice/util/id/IdGenerator.java
  user-service/src/main/java/com/example/userservice/util/id/IdGeneratorByUUID.java
  user-service/src/test/java/com/example/userservice/user/service/JoinUserServiceImplTest.java
Labels: 구현, 리팩토링

#42 docs : update .gitattributes
  .gitattributes
Labels: 문서

#46 [FEAT] User Server - login 서비스 구현하기
  user-service/build.gradle
  user-service/src/main/java/com/example/userservice/UserServiceApplication.java
  user-service/src/main/java/com/example/userservice/config/RedisConfig.java
  user-service/src/main/java/com/example/userservice/config/SecurityConfig.java
  user-service/src/main/java/com/example/userservice/user/controller/UserController.java
  user-service/src/main/java/com/example/userservice/user/controller/UserCreateController.java
  user-service/src/main/java/com/example/userservice/user/controller/port/UserService.java
  user-service/src/main/java/com/example/userservice/user/controller/request/UserLogin.java
  user-service/src/main/java/com/example/userservice/user/controller/response/UserLoginResponse.java
  user-service/src/main/java/com/example/userservice/user/domain/token/Token.java
  user-service/src/main/java/com/example/userservice/user/domain/token/UserWithToken.java
  user-service/src/main/java/com/example/userservice/user/infrastructure/TokenEntity.java
  user-service/src/main/java/com/example/userservice/user/infrastructure/TokenRepositoryImpl.java
  user-service/src/main/java/com/example/userservice/user/infrastructure/UserRepositoryImpl.java
  user-service/src/main/java/com/example/userservice/user/infrastructure/join/UserAuthEntity.java
  user-service/src/main/java/com/example/userservice/user/service/CertificationService.java
  user-service/src/main/java/com/example/userservice/user/service/UserServiceImpl.java
  user-service/src/main/java/com/example/userservice/user/service/auth/JwtTokenServiceImpl.java
  user-service/src/main/java/com/example/userservice/user/service/auth/JwtUtil.java
  user-service/src/main/java/com/example/userservice/user/service/port/JwtTokenService.java
  user-service/src/main/java/com/example/userservice/user/service/port/TokenRepository.java
  user-service/src/main/java/com/example/userservice/user/service/port/UserRepository.java
Labels: 구현

#49 [FEAT] user 서버 구현하기
  user-service/build.gradle
  user-service/src/main/java/com/example/userservice/config/SecurityConfig.java
  user-service/src/main/java/com/example/userservice/user/controller/UserController.java
  user-service/src/main/java/com/example/userservice/user/controller/UserCreateController.java
  user-service/src/main/java/com/example/userservice/user/controller/port/UserService.java
  user-service/src/main/java/com/example/userservice/user/controller/response/UserLoginResponse.java
  user-service/src/main/java/com/example/userservice/user/domain/User.java
  user-service/src/main/java/com/example/userservice/user/domain/UserUpdate.java
  user-service/src/main/java/com/example/userservice/user/dto/request/UserDeleteRequest.java
  user-service/src/main/java/com/example/userservice/user/dto/request/UserLogin.java
  user-service/src/main/java/com/example/userservice/user/dto/request/UserUpdateRequest.java
  user-service/src/main/java/com/example/userservice/user/dto/response/UserJoinResponse.java
  user-service/src/main/java/com/example/userservice/user/dto/response/UserLoginResponse.java
  user-service/src/main/java/com/example/userservice/user/infrastructure/UserEntity.java
  user-service/src/main/java/com/example/userservice/user/infrastructure/UserMongoRepository.java
  user-service/src/main/java/com/example/userservice/user/infrastructure/UserRepositoryImpl.java
  user-service/src/main/java/com/example/userservice/user/infrastructure/join/UserAuthEntity.java
  user-service/src/main/java/com/example/userservice/user/service/UserServiceImpl.java
  user-service/src/main/java/com/example/userservice/user/service/port/UserRepository.java
Labels: 구현, 수정

#57 [FEAT] 채팅메세지 서비스, 컨트롤러, 인프라 구축
  chat-service/src/main/java/org/example/chatservice/chatMessage/controller/ChatMessageController.java
  chat-service/src/main/java/org/example/chatservice/chatMessage/domain/ChatMessage.java
  chat-service/src/main/java/org/example/chatservice/chatMessage/dto/CreateChatMessageRequest.java
  chat-service/src/main/java/org/example/chatservice/chatMessage/dto/addChatMessageRequest.java
  chat-service/src/main/java/org/example/chatservice/chatMessage/infrastructure/repository/ChatMessageMongoRepository.java
  chat-service/src/main/java/org/example/chatservice/chatMessage/infrastructure/repository/ChatMessageRepository.java
  chat-service/src/main/java/org/example/chatservice/chatMessage/infrastructure/repository/ChatMessageRepositoryImpl.java
  chat-service/src/main/java/org/example/chatservice/chatMessage/service/ChatMessageService.java
  chat-service/src/main/java/org/example/chatservice/chatMessage/service/ChatMessageServiceImpl.java
  chat-service/src/main/java/org/example/chatservice/chatRoom/service/ChatRoomServiceImpl.java
  chat-service/src/main/java/org/example/chatservice/error/ResultCode.java
  chat-service/src/test/java/org/example/chatservice/chatMessage/domain/ChatMessageDomainTest.java
  chat-service/src/test/java/org/example/chatservice/chatRoom/controller/ChatControllerTest.java
  chat-service/src/test/java/org/example/chatservice/chatRoom/domain/ChatDomainTest.java
  chat-service/src/test/java/org/example/chatservice/chatRoom/service/ChatRoomServiceTest.java
  chat-service/src/test/java/org/example/chatservice/mock/FakeChatRoomRepository.java
  chat-service/src/test/java/org/example/chatservice/mock/TestContainer.java
Labels: 구현

#58 [FEAT] 유저 서비스 Success/Exception 핸들링 구현 완료
  user-service/src/main/java/com/example/userservice/user/controller/GlobalExceptionHandler.java
  user-service/src/main/java/com/example/userservice/user/controller/UserController.java
  user-service/src/main/java/com/example/userservice/user/controller/UserCreateController.java
  user-service/src/main/java/com/example/userservice/user/controller/response/GlobalResponse.java
  user-service/src/main/java/com/example/userservice/user/controller/response/code/ErrorCode.java
  user-service/src/main/java/com/example/userservice/user/controller/response/code/SuccessCode.java
  user-service/src/main/java/com/example/userservice/user/error/GlobalException.java
  user-service/src/main/java/com/example/userservice/user/service/JoinUserServiceImpl.java
  user-service/src/main/java/com/example/userservice/util/certification/email/EmailCertification.java
Labels: 구현, 리팩토링, 수정

#61 [REFACTOR] 유저 서버 파일 구조 변경
  user-service/src/main/java/com/example/userservice/config/RedisConfig.java
  user-service/src/main/java/com/example/userservice/user/controller/GlobalExceptionHandler.java
  user-service/src/main/java/com/example/userservice/user/controller/UserController.java
  user-service/src/main/java/com/example/userservice/user/controller/UserCreateController.java
  user-service/src/main/java/com/example/userservice/user/controller/port/JoinUserService.java
  user-service/src/main/java/com/example/userservice/user/controller/port/UserService.java
  user-service/src/main/java/com/example/userservice/user/domain/create/UserCreate.java
  user-service/src/main/java/com/example/userservice/user/domain/join/JoinUser.java
  user-service/src/main/java/com/example/userservice/user/dto/request/UserCreateRequest.java
  user-service/src/main/java/com/example/userservice/user/dto/request/UserJoinCertificationRequest.java
  user-service/src/main/java/com/example/userservice/user/dto/request/UserJoinRequest.java
  user-service/src/main/java/com/example/userservice/user/dto/request/UserLoginRequest.java
  user-service/src/main/java/com/example/userservice/user/dto/response/GlobalResponse.java
  user-service/src/main/java/com/example/userservice/user/infrastructure/TokenRepositoryImpl.java
  user-service/src/main/java/com/example/userservice/user/infrastructure/UserMongoRepository.java
  user-service/src/main/java/com/example/userservice/user/infrastructure/UserRepositoryImpl.java
  user-service/src/main/java/com/example/userservice/user/infrastructure/entity/TokenEntity.java
  user-service/src/main/java/com/example/userservice/user/infrastructure/entity/UserEntity.java
  user-service/src/main/java/com/example/userservice/user/infrastructure/join/JoinUserConcurrentMapRepository.java
  user-service/src/main/java/com/example/userservice/user/infrastructure/join/JoinUserRepository.java
  user-service/src/main/java/com/example/userservice/user/service/CertificationService.java
  user-service/src/main/java/com/example/userservice/user/service/JoinUserServiceImpl.java
  user-service/src/main/java/com/example/userservice/user/service/UserServiceImpl.java
  user-service/src/main/java/com/example/userservice/user/service/auth/JwtTokenServiceImpl.java
  user-service/src/main/java/com/example/userservice/user/service/port/TokenRepository.java
  user-service/src/main/java/com/example/userservice/util/certification/email/EmailCertification.java
  user-service/src/main/java/com/example/userservice/util/exception/ErrorCode.java
  user-service/src/main/java/com/example/userservice/util/exception/InputErrorException.java
  user-service/src/main/java/com/example/userservice/util/exception/NotFoundException.java
  user-service/src/main/java/com/example/userservice/util/exception/code/GlobalException.java
  user-service/src/main/java/com/example/userservice/util/exception/code/SuccessCode.java
  user-service/src/test/java/com/example/userservice/user/service/JoinUserServiceImplTest.java
Labels: 구현, 수정

#63 [FEAT] 채팅메세지 소형 테스트 완료
  chat-service/.gradle/8.8/executionHistory/executionHistory.bin
  chat-service/.gradle/8.8/executionHistory/executionHistory.lock
  chat-service/.gradle/8.8/fileHashes/fileHashes.bin
  chat-service/.gradle/8.8/fileHashes/fileHashes.lock
  chat-service/.gradle/8.8/fileHashes/resourceHashesCache.bin
  chat-service/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  chat-service/.gradle/file-system.probe
  chat-service/build/classes/java/test/org/example/chatservice/chatRoom/service/ChatRoomServiceTest.class
  chat-service/build/jacoco/test.exec
  chat-service/build/reports/jacoco/test/jacocoTestReport.xml
  chat-service/build/reports/tests/test/index.html
  chat-service/build/test-results/test/binary/output.bin
  chat-service/build/test-results/test/binary/output.bin.idx
  chat-service/build/test-results/test/binary/results.bin
  chat-service/build/tmp/compileJava/previous-compilation-data.bin
  chat-service/build/tmp/compileTestJava/previous-compilation-data.bin
  chat-service/src/main/java/org/example/chatservice/chatMessage/controller/ChatMessageController.java
  chat-service/src/main/java/org/example/chatservice/chatMessage/infrastructure/repository/ChatMessageMongoRepository.java
  chat-service/src/main/java/org/example/chatservice/chatMessage/infrastructure/repository/ChatMessageRepository.java
  chat-service/src/main/java/org/example/chatservice/chatMessage/infrastructure/repository/ChatMessageRepositoryImpl.java
  chat-service/src/main/java/org/example/chatservice/chatMessage/service/ChatMessageService.java
  chat-service/src/main/java/org/example/chatservice/chatMessage/service/ChatMessageServiceImpl.java
  chat-service/src/test/java/org/example/chatservice/chatMessage/controller/ChatMessageControllerTest.java
  chat-service/src/test/java/org/example/chatservice/chatMessage/domain/ChatMessageDomainTest.java
  chat-service/src/test/java/org/example/chatservice/chatMessage/service/ChatMessageServiceTest.java
  chat-service/src/test/java/org/example/chatservice/chatRoom/controller/ChatControllerTest.java
  chat-service/src/test/java/org/example/chatservice/chatRoom/service/ChatRoomServiceTest.java
  chat-service/src/test/java/org/example/chatservice/mock/FakeChatMessageRepository.java
  chat-service/src/test/java/org/example/chatservice/mock/TestClockHolder.java
  chat-service/src/test/java/org/example/chatservice/mock/TestContainer.java
  chat-service/src/test/java/org/example/chatservice/mock/TestUuidHolder.java
Labels: 구현, 테스트

#65 [FEAT] User Join Service 테스트 구현하기
  user-service/src/main/java/com/example/userservice/user/domain/User.java
  user-service/src/main/java/com/example/userservice/user/domain/create/UserCreate.java
  user-service/src/main/java/com/example/userservice/user/infrastructure/TokenRepositoryImpl.java
  user-service/src/main/java/com/example/userservice/user/infrastructure/entity/TokenEntity.java
  user-service/src/main/java/com/example/userservice/util/exception/ErrorCode.java
  user-service/src/test/java/com/example/userservice/user/domain/UserTest.java
  user-service/src/test/java/com/example/userservice/user/mock/FakeRedisRepository.java
  user-service/src/test/java/com/example/userservice/user/mock/FakeUserDigitRepository.java
  user-service/src/test/java/com/example/userservice/user/mock/FakeUserRepository.java
  user-service/src/test/java/com/example/userservice/user/mock/TestContainer.java
  user-service/src/test/java/com/example/userservice/user/service/JoinUserServiceImplTest.java
Labels: 구현, 테스트, Priority Middle

#72 [DEPLOY] Update chat-service-deploy.yml
  .github/workflows/chat-service-deploy.yml
Labels: 배포

#69 [FEAT] 유저서버 서비스 test 구현 완료
  user-service/src/main/java/com/example/userservice/user/dto/request/UserLoginRequest.java
  user-service/src/main/java/com/example/userservice/user/service/UserServiceImpl.java
  user-service/src/test/java/com/example/userservice/user/mock/FakeUserRepository.java
  user-service/src/test/java/com/example/userservice/user/service/UserServiceImplTest.java
Labels: 구현, 테스트, Priority Middle

#78 [FEAT] Board-service TODO 나누기
  board-service/src/main/java/org/example/boardservice/board/controller/BoardController.java
  board-service/src/main/java/org/example/boardservice/board/controller/CommentController.java
  board-service/src/main/java/org/example/boardservice/board/controller/LabController.java
  board-service/src/main/java/org/example/boardservice/board/domain/Board.java
  board-service/src/main/java/org/example/boardservice/board/domain/Comment.java
  board-service/src/main/java/org/example/boardservice/board/domain/Lab.java
  board-service/src/main/java/org/example/boardservice/board/domain/Like.java
  board-service/src/main/java/org/example/boardservice/board/domain/Recomment.java
  board-service/src/main/java/org/example/boardservice/board/domain/Star.java
  board-service/src/main/java/org/example/boardservice/board/infrastructure/entity/BoardEntity.java
  board-service/src/main/java/org/example/boardservice/board/infrastructure/entity/CommentEntity.java
  board-service/src/main/java/org/example/boardservice/board/infrastructure/entity/LabEntity.java
  board-service/src/main/java/org/example/boardservice/board/infrastructure/entity/LikeEntity.java
  board-service/src/main/java/org/example/boardservice/board/infrastructure/entity/RecommentEntity.java
  board-service/src/main/java/org/example/boardservice/board/infrastructure/entity/StarEntity.java
  board-service/src/main/resources/data.sql
  chat-service/.gradle/8.8/executionHistory/executionHistory.bin
  chat-service/.gradle/8.8/executionHistory/executionHistory.lock
  chat-service/.gradle/8.8/fileHashes/fileHashes.bin
  chat-service/.gradle/8.8/fileHashes/fileHashes.lock
  chat-service/.gradle/8.8/fileHashes/resourceHashesCache.bin
  chat-service/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  chat-service/.gradle/file-system.probe
  chat-service/build/tmp/compileJava/previous-compilation-data.bin
  chat-service/src/main/java/org/example/chatservice/chatMessage/controller/ChatMessageController.java
  chat-service/src/main/java/org/example/chatservice/chatRoom/controller/ChatController.java
Labels: 구현

#79 [FEAT] unversional files 넣기
  board-service/.gitignore
  board-service/build.gradle
  board-service/gradle/wrapper/gradle-wrapper.jar
  board-service/gradle/wrapper/gradle-wrapper.properties
  board-service/gradlew
  board-service/gradlew.bat
  board-service/settings.gradle
  board-service/src/main/java/org/example/boardservice/BoardServiceApplication.java
  board-service/src/main/resources/application.yml
  board-service/src/test/java/org/example/boardservice/BoardServiceApplicationTests.java
Labels: 문서

#83 [FEAT] 게시판 서비스 Domain Entity 확립
  board-service/src/main/java/org/example/boardservice/board/domain/Board.java
  board-service/src/main/java/org/example/boardservice/board/domain/Comment.java
  board-service/src/main/java/org/example/boardservice/board/domain/Lab.java
  board-service/src/main/java/org/example/boardservice/board/domain/Like.java
  board-service/src/main/java/org/example/boardservice/board/domain/Recomment.java
  board-service/src/main/java/org/example/boardservice/board/domain/Star.java
  board-service/src/main/java/org/example/boardservice/board/infrastructure/entity/BoardEntity.java
  board-service/src/main/java/org/example/boardservice/board/infrastructure/entity/CommentEntity.java
  board-service/src/main/java/org/example/boardservice/board/infrastructure/entity/LabEntity.java
  board-service/src/main/java/org/example/boardservice/board/infrastructure/entity/LikeEntity.java
  board-service/src/main/java/org/example/boardservice/board/infrastructure/entity/RecommentEntity.java
  board-service/src/main/java/org/example/boardservice/board/infrastructure/entity/StarEntity.java
  board-service/src/main/java/org/example/boardservice/board/infrastructure/repository/board/BoardJpaRepository.java
  board-service/src/main/java/org/example/boardservice/board/infrastructure/repository/board/BoardRepository.java
  board-service/src/main/java/org/example/boardservice/board/infrastructure/repository/board/BoardRepositoryImpl.java
  board-service/src/main/java/org/example/boardservice/board/infrastructure/repository/lab/LabJpaRepository.java
  board-service/src/main/java/org/example/boardservice/board/infrastructure/repository/lab/LabRepository.java
  board-service/src/main/java/org/example/boardservice/board/infrastructure/repository/lab/LabRepositoryImpl.java
  board-service/src/main/java/org/example/boardservice/utils/ClockHolder.java
  board-service/src/main/java/org/example/boardservice/utils/ClockHolderImpl.java
  board-service/src/main/java/org/example/boardservice/utils/UuidHolder.java
  board-service/src/main/java/org/example/boardservice/utils/UuidHolderImpl.java
  board-service/src/main/resources/data.sql
Labels: 구현, 리팩토링, Prioritoy High
