Repository connetist/connectist-backend, pull requests merged in 2024-07, with the labels that each got.

#84 [DOCS] 배포 파이프 라인 + 아키텍처 ReadME 추가
  README.md
Labels: 문서, 인프라, Priority Low

#86 [Refactor] user service의 DB를 Mysql로 교체한다.
  alarm-service/src/main/java/com/example/alarmservice/alarm/domain/Alarm.java
  alarm-service/src/main/java/com/example/alarmservice/alarm/domain/value/ReceiverInfo.java
  alarm-service/src/main/java/com/example/alarmservice/alarm/dto/request/AlarmRequest.java
  alarm-service/src/main/java/com/example/alarmservice/alarm/dto/request/ReceiverInfoRequest.java
  alarm-service/src/main/java/com/example/alarmservice/alarm/infrastrucutre/TokenRepository.java
  alarm-service/src/main/java/com/example/alarmservice/alarm/infrastrucutre/TokenRepositoryRedis.java
  alarm-service/src/main/java/com/example/alarmservice/alarm/infrastrucutre/entity/TokenEntity.java
  alarm-service/src/main/java/com/example/alarmservice/alarm/infrastrucutre/port/FcmSenderToOne.java
  alarm-service/src/main/java/com/example/alarmservice/alarm/service/AlarmService.java
  alarm-service/src/main/java/com/example/alarmservice/alarm/service/AlarmServiceImpl.java
  alarm-service/src/main/java/com/example/alarmservice/config/RedisConfig.java
  alarm-service/src/main/java/com/example/alarmservice/util/ClockHolder.java
  alarm-service/src/main/java/com/example/alarmservice/util/ClockHolderUnixTime.java
  board-service/src/main/java/org/example/boardservice/board/domain/Lab.java
  board-service/src/main/java/org/example/boardservice/board/domain/Recomment.java
  board-service/src/main/java/org/example/boardservice/board/domain/Star.java
  board-service/src/main/java/org/example/boardservice/board/domain/enuminfo/Major.java
  board-service/src/main/java/org/example/boardservice/board/domain/enuminfo/School.java
  board-service/src/main/java/org/example/boardservice/board/infrastructure/entity/LabEntity.java
  board-service/src/main/java/org/example/boardservice/board/infrastructure/entity/StarEntity.java
  board-service/src/main/resources/application.yml
  board-service/src/main/resources/data.sql
  user-service/build.gradle
  user-service/src/main/java/com/example/userservice/UserServiceApplication.java
  user-service/src/main/java/com/example/userservice/user/controller/UserController.java
  user-service/src/main/java/com/example/userservice/user/infrastructure/UserJpaRepository.java
  user-service/src/main/java/com/example/userservice/user/infrastructure/UserMongoRepository.java
  user-service/src/main/java/com/example/userservice/user/infrastructure/UserRepositoryImpl.java
  user-service/src/main/java/com/example/userservice/user/infrastructure/entity/UserEntity.java
  user-service/src/main/java/com/example/userservice/user/service/UserServiceImpl.java
Labels: 구현, 리팩토링, Prioritoy High

#91 [FEAT] Lab Controller, Service, Infrastructure에 대한 단위 테스트코드 작성
  board-service/src/test/java/org/example/boardservice/lab/controller/LabControllerTest.java
Labels: 구현, 테스트, Priority Low

#92 [FIX] Board-service StarEntity merge conflict 해결
  board-service/src/main/java/org/example/boardservice/board/infrastructure/entity/StarEntity.java
Labels: 수정

#93 [DEPLOY] board-service, chat-service CI 파이프라인 수정
  .github/workflows/board-service-deploy.yml
  .github/workflows/chat-service-deploy.yml
  board-service/src/main/java/org/example/boardservice/board/infrastructure/entity/StarEntity.java
  k8s/board-service/deployment.yaml
  k8s/board-service/service.yaml
Labels: 문서, 배포, Priority Low

#94 [DEPLOY]: chat-service CI/CD yaml 파일 구축
  .github/workflows/board-service-deploy.yml
  .github/workflows/chat-service-deploy.yml
  k8s/chat-service/deployment.yaml
  k8s/chat-service/service.yaml
Labels: 문서, 배포

#95 [DEPLOY] board-service CI test
  board-service/src/test/java/org/example/boardservice/lab/domain/LabDomainTest.java
Labels: 배포, 인프라

#96 [DEPLOY] chat-service , board-service CI jobs-build-runs-on 변경
  .github/workflows/board-service-deploy.yml
  .github/workflows/chat-service-deploy.yml
Labels: 버그, 배포, Prioritoy High

#97 [DEPLOY] : board-service ci test -2
  board-service/src/test/java/org/example/boardservice/lab/domain/LabDomainTest.java
Labels: 문서, 배포, Priority Low

#98 [DEPLOY] board-service Application-test의 불필요한 부분 삭제 - 2
  board-service/src/test/java/org/example/boardservice/BoardServiceApplicationTests.java
  board-service/src/test/java/org/example/boardservice/lab/service/LabServiceTest.java
Labels: 버그, 수정, 테스트, Priority Low

#104 [TEST] Jacoco Test Coverage 측정 yaml 생성
  .github/workflows/board-service-test-coverage.yml
  board-service/build.gradle
  chat-service/.gradle/8.8/executionHistory/executionHistory.bin
  chat-service/.gradle/8.8/executionHistory/executionHistory.lock
  chat-service/.gradle/8.8/fileHashes/fileHashes.bin
  chat-service/.gradle/8.8/fileHashes/fileHashes.lock
  chat-service/.gradle/8.8/fileHashes/resourceHashesCache.bin
  chat-service/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  chat-service/.gradle/file-system.probe
  chat-service/build/jacoco/test.exec
  chat-service/build/reports/jacoco/test/jacocoTestReport.xml
  chat-service/build/reports/tests/test/index.html
  chat-service/build/tmp/compileTestJava/previous-compilation-data.bin
  eureka-service/.gitignore
  eureka-service/build.gradle
  eureka-service/gradle/wrapper/gradle-wrapper.jar
  eureka-service/gradle/wrapper/gradle-wrapper.properties
  eureka-service/gradlew
  eureka-service/gradlew.bat
  eureka-service/settings.gradle
  eureka-service/src/main/java/org/example/eurekaservice/EurekaServiceApplication.java
  eureka-service/src/main/resources/application.yaml
  eureka-service/src/test/java/org/example/eurekaservice/EurekaServiceApplicationTests.java
Labels: 구현, 세팅, 테스트, Priority Low

#106 [FEAT] Eureka-service 생성
  .github/workflows/chat-service-deploy.yml
  eureka-service/src/main/resources/application.yaml
Labels: 구현, 리팩토링, 배포, Priority Low

#110 [FEAT] api-gateway service 생성
  .github/workflows/board-service-test-coverage.yml
  apigateway-service/.gitignore
  apigateway-service/build.gradle
  apigateway-service/gradle/wrapper/gradle-wrapper.jar
  apigateway-service/gradle/wrapper/gradle-wrapper.properties
  apigateway-service/gradlew
  apigateway-service/gradlew.bat
  apigateway-service/settings.gradle
  apigateway-service/src/main/java/org/example/apigatewayservice/ApigatewayServiceApplication.java
  apigateway-service/src/main/java/org/example/apigatewayservice/filter/AuthorizationHeaderFilter.java
  apigateway-service/src/main/java/org/example/apigatewayservice/filter/GlobalFilter.java
  apigateway-service/src/main/resources/application.yaml
  apigateway-service/src/test/java/org/example/apigatewayservice/ApigatewayServiceApplicationTests.java
  board-service/src/main/resources/application.yml
  user-service/build.gradle
Labels: 구현, Priority Middle

#112 [FEAT] Admin user sql제작
  user-service/src/main/java/com/example/userservice/user/infrastructure/entity/UserEntity.java
  user-service/src/main/resources/data.sql
Labels: 구현, Priority Low

#114 [FEAT] User service에 admin mock data 만들어 넣기
  board-service/src/main/java/org/example/boardservice/board/controller/BoardController.java
  board-service/src/main/java/org/example/boardservice/board/dto/request/board/BoardDeleteRequest.java
  board-service/src/main/java/org/example/boardservice/board/infrastructure/entity/CommentEntity.java
  board-service/src/main/java/org/example/boardservice/board/infrastructure/repository/board/BoardJpaRepository.java
  board-service/src/main/java/org/example/boardservice/board/infrastructure/repository/board/BoardRepositoryImpl.java
  board-service/src/main/java/org/example/boardservice/board/infrastructure/repository/board/BoardSpecs.java
  board-service/src/main/java/org/example/boardservice/board/infrastructure/repository/comment/CommentJpaRepository.java
  board-service/src/main/java/org/example/boardservice/board/infrastructure/repository/comment/CommentRepositoryImpl.java
  board-service/src/main/java/org/example/boardservice/board/infrastructure/repository/comment/CommentReposotiry.java
  board-service/src/main/java/org/example/boardservice/board/infrastructure/repository/comment/CommentSpecs.java
  board-service/src/main/java/org/example/boardservice/board/service/BoardServiceImpl.java
  board-service/src/main/java/org/example/boardservice/error/ResultCode.java
  board-service/src/main/java/org/example/boardservice/utils/requestverify/RequestCheck.java
  board-service/src/main/resources/application.yml
  user-service/src/.DS_Store
  user-service/src/main/.DS_Store
  user-service/src/main/java/com/example/userservice/config/DataInitializer.java
  user-service/src/main/java/com/example/userservice/user/service/UserServiceImpl.java
  user-service/src/main/resources/data.sql
  user-service/src/test/java/com/example/userservice/util/PasswordTest.java
Labels: 구현

#115 [FEAT] api-gateway Authorization Filter 추가
  apigateway-service/.gradle/8.8/executionHistory/executionHistory.bin
  apigateway-service/.gradle/8.8/executionHistory/executionHistory.lock
  apigateway-service/.gradle/8.8/fileHashes/fileHashes.bin
  apigateway-service/.gradle/8.8/fileHashes/fileHashes.lock
  apigateway-service/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  apigateway-service/.gradle/file-system.probe
  apigateway-service/build/resources/main/application.yaml
  apigateway-service/src/main/resources/application.yaml
  board-service/src/main/java/org/example/boardservice/board/domain/Lab.java
  board-service/src/main/java/org/example/boardservice/utils/ClockHolder.java
  board-service/src/test/java/org/example/boardservice/lab/domain/LabDomainTest.java
  board-service/src/test/java/org/example/boardservice/lab/service/LabServiceTest.java
  board-service/src/test/java/org/example/boardservice/mock/TestClockHolder.java
  chat-service/.gradle/8.8/executionHistory/executionHistory.bin
  chat-service/.gradle/8.8/executionHistory/executionHistory.lock
  chat-service/.gradle/8.8/fileHashes/fileHashes.bin
  chat-service/.gradle/8.8/fileHashes/fileHashes.lock
  chat-service/.gradle/8.8/fileHashes/resourceHashesCache.bin
  chat-service/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  chat-service/.gradle/file-system.probe
  chat-service/build/jacoco/test.exec
  chat-service/build/reports/jacoco/test/jacocoTestReport.xml
  chat-service/build/reports/tests/test/index.html
  chat-service/build/test-results/test/binary/output.bin
  chat-service/build/test-results/test/binary/output.bin.idx
  chat-service/build/tmp/compileTestJava/previous-compilation-data.bin
  chat-service/src/main/java/org/example/chatservice/chatRoom/domain/ChatRoom.java
  chat-service/src/test/java/org/example/chatservice/chatRoom/domain/ChatDomainTest.java
  chat-service/src/test/java/org/example/chatservice/chatRoom/service/ChatRoomServiceTest.java
  user-service/src/main/resources/data.sql
Labels: 구현, Priority Low

#117 [FIX] deleted된 recomment가 return되지 않도록 하기
  board-service/src/main/java/org/example/boardservice/board/domain/Comment.java
  board-service/src/main/java/org/example/boardservice/board/infrastructure/repository/comment/CommentRepositoryImpl.java
  board-service/src/main/java/org/example/boardservice/board/service/CommentServiceImpl.java
Labels: 구현, 버그, Prioritoy High

#120 [REFACTOR] 프로젝트 폴더 구조 변경하기
  board-service/src/main/java/org/example/boardservice/board/controller/BoardController.java
  board-service/src/main/java/org/example/boardservice/board/controller/CommentController.java
  board-service/src/main/java/org/example/boardservice/board/controller/LabController.java
  board-service/src/main/java/org/example/boardservice/board/domain/Board.java
  board-service/src/main/java/org/example/boardservice/board/domain/Comment.java
  board-service/src/main/java/org/example/boardservice/board/domain/Like.java
  board-service/src/main/java/org/example/boardservice/board/domain/Recomment.java
  board-service/src/main/java/org/example/boardservice/board/dto/request/lab/LabAddStarRequest.java
  board-service/src/main/java/org/example/boardservice/board/dto/request/lab/LabRemoveStarRequest.java
  board-service/src/main/java/org/example/boardservice/board/dto/request/lab/LabSchoolAndMajorRequest.java
  board-service/src/main/java/org/example/boardservice/board/dto/request/lab/LabUpdateStarRequest.java
  board-service/src/main/java/org/example/boardservice/board/service/board/BoardService.java
  board-service/src/main/java/org/example/boardservice/board/service/board/BoardServiceImpl.java
  board-service/src/main/java/org/example/boardservice/board/service/comment/CommentService.java
  board-service/src/main/java/org/example/boardservice/board/service/comment/CommentServiceImpl.java
  board-service/src/main/java/org/example/boardservice/board/service/lab/LabService.java
  board-service/src/main/java/org/example/boardservice/board/service/lab/LabServiceImpl.java
  board-service/src/main/java/org/example/boardservice/utils/clock/ClockHolder.java
  board-service/src/main/java/org/example/boardservice/utils/clock/ClockHolderImpl.java
  board-service/src/main/java/org/example/boardservice/utils/uuid/UuidHolder.java
  board-service/src/main/java/org/example/boardservice/utils/uuid/UuidHolderImpl.java
  board-service/src/test/java/org/example/boardservice/lab/controller/LabControllerTest.java
  board-service/src/test/java/org/example/boardservice/lab/domain/LabDomainTest.java
  board-service/src/test/java/org/example/boardservice/lab/service/LabServiceTest.java
  board-service/src/test/java/org/example/boardservice/mock/TestClockHolder.java
  board-service/src/test/java/org/example/boardservice/mock/TestContainer.java
  board-service/src/test/java/org/example/boardservice/mock/TestUuidHolder.java
Labels: 리팩토링

#118 fix: chat-service 서비스 문자열 비교 수정
  chat-service/.gradle/8.8/executionHistory/executionHistory.bin
  chat-service/.gradle/8.8/executionHistory/executionHistory.lock
  chat-service/.gradle/8.8/fileHashes/fileHashes.bin
  chat-service/.gradle/8.8/fileHashes/fileHashes.lock
  chat-service/.gradle/8.8/fileHashes/resourceHashesCache.bin
  chat-service/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  chat-service/build/tmp/compileJava/previous-compilation-data.bin
  chat-service/src/main/java/org/example/chatservice/chatRoom/service/ChatRoomServiceImpl.java
Labels: 수정, Prioritoy High

#125 [FIX] board-service 전체 수정
  board-service/src/main/java/org/example/boardservice/board/controller/BoardController.java
  board-service/src/main/java/org/example/boardservice/board/controller/CommentController.java
  board-service/src/main/java/org/example/boardservice/board/domain/Lab.java
  board-service/src/main/java/org/example/boardservice/board/domain/Recomment.java
  board-service/src/main/java/org/example/boardservice/board/dto/request/board/BoardDeleteRequest.java
  board-service/src/main/java/org/example/boardservice/board/dto/request/board/BoardLikeRequest.java
  board-service/src/main/java/org/example/boardservice/board/dto/request/comment/CommentDeleteRequest.java
  board-service/src/main/java/org/example/boardservice/board/infrastructure/entity/RecommentEntity.java
  board-service/src/main/java/org/example/boardservice/board/infrastructure/repository/comment/CommentRepositoryImpl.java
  board-service/src/main/java/org/example/boardservice/board/service/board/BoardService.java
  board-service/src/main/java/org/example/boardservice/board/service/board/BoardServiceImpl.java
  board-service/src/main/java/org/example/boardservice/board/service/comment/CommentService.java
  board-service/src/main/java/org/example/boardservice/board/service/comment/CommentServiceImpl.java
  board-service/src/main/java/org/example/boardservice/board/service/lab/LabServiceImpl.java
  board-service/src/main/resources/application.yml
  board-service/src/test/java/org/example/boardservice/lab/domain/LabDomainTest.java
Labels: 구현, 리팩토링, 수정, Prioritoy High

#137 [REFACTOR] board service controller, service, domain 리팩토링
  board-service/src/main/java/org/example/boardservice/board/controller/BoardController.java
  board-service/src/main/java/org/example/boardservice/board/controller/CommentController.java
  board-service/src/main/java/org/example/boardservice/board/domain/Board.java
  board-service/src/main/java/org/example/boardservice/board/domain/Comment.java
  board-service/src/main/java/org/example/boardservice/board/domain/Recomment.java
  board-service/src/main/java/org/example/boardservice/board/dto/request/comment/CommentDeleteRequest.java
  board-service/src/main/java/org/example/boardservice/board/dto/request/comment/create/CommentRequest.java
  board-service/src/main/java/org/example/boardservice/board/dto/request/comment/create/RecommentRequest.java
  board-service/src/main/java/org/example/boardservice/board/dto/request/comment/delete/CommentDeleteRequest.java
  board-service/src/main/java/org/example/boardservice/board/dto/request/comment/delete/RecommentDeleteRequest.java
  board-service/src/main/java/org/example/boardservice/board/dto/request/comment/like/CommentLikeRequest.java
  board-service/src/main/java/org/example/boardservice/board/infrastructure/repository/comment/CommentRepositoryImpl.java
  board-service/src/main/java/org/example/boardservice/board/infrastructure/repository/comment/CommentReposotiry.java
  board-service/src/main/java/org/example/boardservice/board/service/board/BoardService.java
  board-service/src/main/java/org/example/boardservice/board/service/board/BoardServiceImpl.java
  board-service/src/main/java/org/example/boardservice/board/service/comment/CommentService.java
  board-service/src/main/java/org/example/boardservice/board/service/comment/CommentServiceImpl.java
Labels: 리팩토링, Prioritoy High

#139 [TEST] 게시글 도메인, 서비스 테스트
  board-service/src/main/java/org/example/boardservice/board/controller/BoardController.java
  board-service/src/main/java/org/example/boardservice/board/dto/request/board/BoardDeleteRequest.java
  board-service/src/main/java/org/example/boardservice/board/dto/request/board/BoardLikeRequest.java
  board-service/src/main/java/org/example/boardservice/board/dto/request/board/BoardRequest.java
  board-service/src/main/java/org/example/boardservice/board/dto/request/comment/create/CommentRequest.java
  board-service/src/main/java/org/example/boardservice/board/dto/request/comment/create/RecommentRequest.java
  board-service/src/main/java/org/example/boardservice/board/dto/request/comment/delete/CommentDeleteRequest.java
  board-service/src/main/java/org/example/boardservice/board/dto/request/comment/delete/RecommentDeleteRequest.java
  board-service/src/main/java/org/example/boardservice/board/dto/request/comment/like/CommentLikeRequest.java
  board-service/src/main/java/org/example/boardservice/board/service/board/BoardService.java
  board-service/src/main/java/org/example/boardservice/board/service/board/BoardServiceImpl.java
  board-service/src/main/java/org/example/boardservice/board/service/comment/CommentService.java
  board-service/src/main/java/org/example/boardservice/board/service/comment/CommentServiceImpl.java
  board-service/src/test/java/org/example/boardservice/board/domain/BoardDomainTest.java
  board-service/src/test/java/org/example/boardservice/board/service/BoardServiceTest.java
  board-service/src/test/java/org/example/boardservice/comment/domain/CommentDomainTest.java
  board-service/src/test/java/org/example/boardservice/comment/service/CommentServiceTest.java
  board-service/src/test/java/org/example/boardservice/mock/FakeBoardRepository.java
  board-service/src/test/java/org/example/boardservice/mock/FakeCommentRepository.java
Labels: 구현, 테스트, Priority Low

#141 [FEAT] User Service Health Check추가하기
  user-service/src/main/java/com/example/userservice/user/controller/token/TokenController.java
  user-service/src/main/java/com/example/userservice/user/controller/user/UserController.java
  user-service/src/main/java/com/example/userservice/user/dto/response/token/TokenResponse.java
  user-service/src/main/java/com/example/userservice/user/service/token/JwtTokenService.java
  user-service/src/main/java/com/example/userservice/user/service/token/JwtTokenServiceImpl.java
Labels: 구현, Priority Middle

#143 [FEAT] Authorization Filter의 JWT 인증로직 추가
  apigateway-service/build.gradle
  apigateway-service/src/main/java/org/example/apigatewayservice/ApigatewayServiceApplication.java
  apigateway-service/src/main/java/org/example/apigatewayservice/feign/TokenClient.java
  apigateway-service/src/main/java/org/example/apigatewayservice/filter/AuthorizationHeaderFilter.java
  apigateway-service/src/main/java/org/example/apigatewayservice/response/TokenResponse.java
  apigateway-service/src/main/resources/application.yaml
  user-service/src/main/java/com/example/userservice/util/token/JwtUtil.java
Labels: 구현, Priority Middle

#146 [FEAT] Spring gateway를 통해서 access token을 검증하고, user service와 통신하여 refresh token, access token을 새로 발급받기
  apigateway-service/build.gradle
  apigateway-service/src/main/java/org/example/apigatewayservice/config/FeignClientConfig.java
  apigateway-service/src/main/java/org/example/apigatewayservice/dto/request/TokenRequest.java
  apigateway-service/src/main/java/org/example/apigatewayservice/dto/response/Token.java
  apigateway-service/src/main/java/org/example/apigatewayservice/dto/response/TokenResponse.java
  apigateway-service/src/main/java/org/example/apigatewayservice/feign/TokenClient.java
  apigateway-service/src/main/java/org/example/apigatewayservice/filter/AuthorizationHeaderFilter.java
  apigateway-service/src/main/java/org/example/apigatewayservice/response/TokenResponse.java
  apigateway-service/src/main/java/org/example/apigatewayservice/util/Token.java
  apigateway-service/src/main/resources/application.yaml
  user-service/src/main/java/com/example/userservice/config/RedisConfig.java
  user-service/src/main/java/com/example/userservice/config/SecurityConfig.java
  user-service/src/main/java/com/example/userservice/user/controller/token/TokenController.java
  user-service/src/main/java/com/example/userservice/user/infrastructure/token/TokenRepositoryImpl.java
  user-service/src/main/java/com/example/userservice/user/service/token/JwtTokenServiceImpl.java
  user-service/src/main/java/com/example/userservice/util/token/JwtUtil.java
Labels: 구현, 리팩토링, Prioritoy High

#148 [REFACTOR]: cloud gateway에서 cookie업데이트 하기
  apigateway-service/src/main/java/org/example/apigatewayservice/filter/AuthorizationHeaderFilter.java
  apigateway-service/src/main/java/org/example/apigatewayservice/filter/StickySessionFilter.java
  apigateway-service/src/main/resources/application.yaml
  user-service/src/main/java/com/example/userservice/user/domain/user/User.java
  user-service/src/main/java/com/example/userservice/user/domain/user/value/UserDegree.java
  user-service/src/main/java/com/example/userservice/user/domain/user/value/UserMajor.java
  user-service/src/main/java/com/example/userservice/user/domain/user/value/UserSex.java
  user-service/src/main/java/com/example/userservice/user/domain/user/value/UserStatus.java
  user-service/src/main/java/com/example/userservice/user/dto/request/user/UserCreateRequest.java
  user-service/src/main/java/com/example/userservice/user/service/token/JwtTokenServiceImpl.java
  user-service/src/main/java/com/example/userservice/user/service/user/mail/UserCertificationService.java
  user-service/src/test/java/com/example/userservice/user/service/UserServiceImplTest.java
Labels: 리팩토링, Priority Middle

#153 [FEAT] board,chat service eureka client로 등록하고 api-gateway에 연결하기
  apigateway-service/src/main/java/org/example/apigatewayservice/filter/AuthorizationHeaderFilter.java
  apigateway-service/src/main/resources/application.yaml
  board-service/build.gradle
  board-service/src/main/java/org/example/boardservice/BoardServiceApplication.java
  board-service/src/main/java/org/example/boardservice/board/controller/BoardController.java
  board-service/src/main/java/org/example/boardservice/board/infrastructure/repository/board/BoardRepositoryImpl.java
  board-service/src/main/java/org/example/boardservice/board/service/comment/CommentServiceImpl.java
  board-service/src/main/java/org/example/boardservice/error/GlobalException.java
  board-service/src/main/java/org/example/boardservice/error/ResultCode.java
  board-service/src/main/java/org/example/boardservice/utils/PortListener.java
  board-service/src/main/resources/application.yml
  board-service/src/test/java/org/example/boardservice/comment/service/CommentServiceTest.java
  chat-service/build.gradle
  chat-service/src/main/java/org/example/chatservice/ChatServiceApplication.java
  chat-service/src/main/resources/application.yaml
  user-service/src/main/java/com/example/userservice/user/controller/user/UserController.java
Labels: 구현, Prioritoy High
